version: '3.9'

services:
  web:
    build: ./
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./:/app/
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
  static_volume:
  media_volume:
