# Generated by Django 4.0.6 on 2022-07-14 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 14, 16, 9, 41, 52266), editable=False),
        ),
    ]
