# Generated by Django 4.0.6 on 2022-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.FileField(upload_to="%Y/%m/%d"),
        ),
    ]
