# Generated by Django 4.0.6 on 2022-08-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folder", "0001_initial"),
        ("document", "0002_alter_document_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="folder.folder",
            ),
        ),
    ]
